AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-typescrip-api

  Sample SAM Template for sam-typescrip-api

Parameters:
  Dialect:
    Type: String
    Default: ""
  Host:
    Type: String
    Default: ""
  Port:
    Type: Number
    Default: 5432
  Logging:
    Type: String
    Default: ""
  UserName:
    Type: String
    Default: ""
  Password:
    Type: String
    Default: ""

Globals:
  Function:
    Timeout: 3
    Tracing: Active
    Environment:
      DIALECT: !Ref Dialect
      HOST: !Ref Host
      PORT: !Ref Port
      LOGGING: !Ref Logging
      USERNAME: !Ref UserName
      PASSWORD: !Ref Password
  Api:
    TracingEnabled: True

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,POST, PUT,GET, DELETE'"
        AllowHeaders: "'Content-Type,Authorization, X-Amz-Date,X-Esmt-Application'"
        AllowOrigin: "'*'"

Resources:
  GetProductsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: dist/app.getProducts
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      Events:
        GetProducts:
          Type: Api
          Properties:
            Path: /products
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CrudProductsApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/products"
